//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotTimeWork.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotTimeWork.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shows details of a specific Task. ähnelt.
        /// </summary>
        internal static string Details_Description {
            get {
                return ResourceManager.GetString("Details_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Developer config file already exists. Overwrite it... ähnelt.
        /// </summary>
        internal static string Developer_Create_ExistsAlready {
            get {
                return ResourceManager.GetString("Developer_Create_ExistsAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Developer config file created successfully. ähnelt.
        /// </summary>
        internal static string Developer_Create_Success {
            get {
                return ResourceManager.GetString("Developer_Create_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Creates Developer Config file. This will create a new developer config file in the current directory. The config file will be used to store the developer settings. ähnelt.
        /// </summary>
        internal static string Developer_Description {
            get {
                return ResourceManager.GetString("Developer_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Task is available. ähnelt.
        /// </summary>
        internal static string General_NoTaskAvailable {
            get {
                return ResourceManager.GetString("General_NoTaskAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Developer ähnelt.
        /// </summary>
        internal static string List_Column_Developer {
            get {
                return ResourceManager.GetString("List_Column_Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Focus Working Time (Minutes) ähnelt.
        /// </summary>
        internal static string List_Column_FocusTime {
            get {
                return ResourceManager.GetString("List_Column_FocusTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start Time ähnelt.
        /// </summary>
        internal static string List_Column_StartTime {
            get {
                return ResourceManager.GetString("List_Column_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Task Name ähnelt.
        /// </summary>
        internal static string List_Column_TaskName {
            get {
                return ResourceManager.GetString("List_Column_TaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Working Time (Minutes) ähnelt.
        /// </summary>
        internal static string List_Column_WorkingTime {
            get {
                return ResourceManager.GetString("List_Column_WorkingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lists all tasks. This will list all tasks in the current project. The tasks will be listed in the order they were created. ähnelt.
        /// </summary>
        internal static string List_Description {
            get {
                return ResourceManager.GetString("List_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description: ähnelt.
        /// </summary>
        internal static string Project_Ask_Description {
            get {
                return ResourceManager.GetString("Project_Ask_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project end date (yyyy-MM-dd or EMPTY for N/A): ähnelt.
        /// </summary>
        internal static string Project_Ask_EndDate {
            get {
                return ResourceManager.GetString("Project_Ask_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project Name: ähnelt.
        /// </summary>
        internal static string Project_Ask_Name {
            get {
                return ResourceManager.GetString("Project_Ask_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project start date: ähnelt.
        /// </summary>
        internal static string Project_Ask_StartDate {
            get {
                return ResourceManager.GetString("Project_Ask_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Max time per day (in hours): ähnelt.
        /// </summary>
        internal static string Project_Ask_TimePerDay {
            get {
                return ResourceManager.GetString("Project_Ask_TimePerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Task ID to create: ähnelt.
        /// </summary>
        internal static string StartTask_CreateTask {
            get {
                return ResourceManager.GetString("StartTask_CreateTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Task &apos;{0}&apos; already exists. Please enter a different task ID. ähnelt.
        /// </summary>
        internal static string StartTask_CreateTask_Failed {
            get {
                return ResourceManager.GetString("StartTask_CreateTask_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Small Task Description: ähnelt.
        /// </summary>
        internal static string StartTask_CreateTask_SmallDescription {
            get {
                return ResourceManager.GetString("StartTask_CreateTask_SmallDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Can start / mark TimeStamp when a new Task was started working on. ähnelt.
        /// </summary>
        internal static string StartTask_Description {
            get {
                return ResourceManager.GetString("StartTask_Description", resourceCulture);
            }
        }
    }
}
